{"name": "Попытка принять заказ с несуществующим id курьера", "status": "passed", "steps": [{"name": "Принятие заказа", "status": "passed", "parameters": [{"name": "order_id", "value": "492289"}, {"name": "courier_id", "value": "0"}], "start": 1750763686184, "stop": 1750763686361}], "start": 1750763686184, "stop": 1750763686362, "uuid": "c5835cd4-7197-4341-a924-15339a5b9aa5", "historyId": "d03b297427821b50f83041d0d54214a5", "testCaseId": "d03b297427821b50f83041d0d54214a5", "fullName": "tests.orders.test_accept_order.TestAcceptOrder#test_accept_order_courier_id_are_not_valid_error", "labels": [{"name": "feature", "value": "Принятие заказа"}, {"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-BQGT2AEK"}, {"name": "thread", "value": "18804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_accept_order"}]}